# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plotter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='plotter.proto',
  package='pb.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rplotter.proto\x12\x05pb.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa8\x02\n\x0e\x42\x61rPlotRequest\x12*\n\tdataframe\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x01x\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x0e\n\x01y\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x03hue\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\r\n\x05order\x18\x05 \x03(\t\x12,\n\x06orient\x18\x06 \x01(\x0e\x32\x1c.pb.v1.BarPlotRequest.Orient\x12\x0f\n\x05\x63olor\x18\x07 \x01(\tH\x00\x12\x11\n\x07palette\x18\x08 \x01(\tH\x00\x12\x12\n\nsaturation\x18\t \x01(\x02\"&\n\x06Orient\x12\x0c\n\x08VERTICAL\x10\x00\x12\x0e\n\nHORIZONTAL\x10\x01\x42\x07\n\x05styleB\x04\n\x02_xB\x04\n\x02_yB\x06\n\x04_hue\" \n\x0f\x42\x61rPlotResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\"B\n\x14\x43ircleDiagramRequest\x12*\n\tdataframe\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"&\n\x15\x43ircleDiagramResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\x93\x01\n\x07Plotter\x12:\n\x07\x42\x61rPlot\x12\x15.pb.v1.BarPlotRequest\x1a\x16.pb.v1.BarPlotResponse\"\x00\x12L\n\rCircleDiagram\x12\x1b.pb.v1.CircleDiagramRequest\x1a\x1c.pb.v1.CircleDiagramResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])



_BARPLOTREQUEST_ORIENT = _descriptor.EnumDescriptor(
  name='Orient',
  full_name='pb.v1.BarPlotRequest.Orient',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERTICAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HORIZONTAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=284,
  serialized_end=322,
)
_sym_db.RegisterEnumDescriptor(_BARPLOTREQUEST_ORIENT)


_BARPLOTREQUEST = _descriptor.Descriptor(
  name='BarPlotRequest',
  full_name='pb.v1.BarPlotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataframe', full_name='pb.v1.BarPlotRequest.dataframe', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='pb.v1.BarPlotRequest.x', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='pb.v1.BarPlotRequest.y', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hue', full_name='pb.v1.BarPlotRequest.hue', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='pb.v1.BarPlotRequest.order', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orient', full_name='pb.v1.BarPlotRequest.orient', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='pb.v1.BarPlotRequest.color', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='palette', full_name='pb.v1.BarPlotRequest.palette', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='saturation', full_name='pb.v1.BarPlotRequest.saturation', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BARPLOTREQUEST_ORIENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='style', full_name='pb.v1.BarPlotRequest.style',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_x', full_name='pb.v1.BarPlotRequest._x',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_y', full_name='pb.v1.BarPlotRequest._y',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_hue', full_name='pb.v1.BarPlotRequest._hue',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=55,
  serialized_end=351,
)


_BARPLOTRESPONSE = _descriptor.Descriptor(
  name='BarPlotResponse',
  full_name='pb.v1.BarPlotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='pb.v1.BarPlotResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=385,
)


_CIRCLEDIAGRAMREQUEST = _descriptor.Descriptor(
  name='CircleDiagramRequest',
  full_name='pb.v1.CircleDiagramRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataframe', full_name='pb.v1.CircleDiagramRequest.dataframe', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=453,
)


_CIRCLEDIAGRAMRESPONSE = _descriptor.Descriptor(
  name='CircleDiagramResponse',
  full_name='pb.v1.CircleDiagramResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='pb.v1.CircleDiagramResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=493,
)

_BARPLOTREQUEST.fields_by_name['dataframe'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_BARPLOTREQUEST.fields_by_name['orient'].enum_type = _BARPLOTREQUEST_ORIENT
_BARPLOTREQUEST_ORIENT.containing_type = _BARPLOTREQUEST
_BARPLOTREQUEST.oneofs_by_name['style'].fields.append(
  _BARPLOTREQUEST.fields_by_name['color'])
_BARPLOTREQUEST.fields_by_name['color'].containing_oneof = _BARPLOTREQUEST.oneofs_by_name['style']
_BARPLOTREQUEST.oneofs_by_name['style'].fields.append(
  _BARPLOTREQUEST.fields_by_name['palette'])
_BARPLOTREQUEST.fields_by_name['palette'].containing_oneof = _BARPLOTREQUEST.oneofs_by_name['style']
_BARPLOTREQUEST.oneofs_by_name['_x'].fields.append(
  _BARPLOTREQUEST.fields_by_name['x'])
_BARPLOTREQUEST.fields_by_name['x'].containing_oneof = _BARPLOTREQUEST.oneofs_by_name['_x']
_BARPLOTREQUEST.oneofs_by_name['_y'].fields.append(
  _BARPLOTREQUEST.fields_by_name['y'])
_BARPLOTREQUEST.fields_by_name['y'].containing_oneof = _BARPLOTREQUEST.oneofs_by_name['_y']
_BARPLOTREQUEST.oneofs_by_name['_hue'].fields.append(
  _BARPLOTREQUEST.fields_by_name['hue'])
_BARPLOTREQUEST.fields_by_name['hue'].containing_oneof = _BARPLOTREQUEST.oneofs_by_name['_hue']
_CIRCLEDIAGRAMREQUEST.fields_by_name['dataframe'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['BarPlotRequest'] = _BARPLOTREQUEST
DESCRIPTOR.message_types_by_name['BarPlotResponse'] = _BARPLOTRESPONSE
DESCRIPTOR.message_types_by_name['CircleDiagramRequest'] = _CIRCLEDIAGRAMREQUEST
DESCRIPTOR.message_types_by_name['CircleDiagramResponse'] = _CIRCLEDIAGRAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BarPlotRequest = _reflection.GeneratedProtocolMessageType('BarPlotRequest', (_message.Message,), {
  'DESCRIPTOR' : _BARPLOTREQUEST,
  '__module__' : 'plotter_pb2'
  # @@protoc_insertion_point(class_scope:pb.v1.BarPlotRequest)
  })
_sym_db.RegisterMessage(BarPlotRequest)

BarPlotResponse = _reflection.GeneratedProtocolMessageType('BarPlotResponse', (_message.Message,), {
  'DESCRIPTOR' : _BARPLOTRESPONSE,
  '__module__' : 'plotter_pb2'
  # @@protoc_insertion_point(class_scope:pb.v1.BarPlotResponse)
  })
_sym_db.RegisterMessage(BarPlotResponse)

CircleDiagramRequest = _reflection.GeneratedProtocolMessageType('CircleDiagramRequest', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLEDIAGRAMREQUEST,
  '__module__' : 'plotter_pb2'
  # @@protoc_insertion_point(class_scope:pb.v1.CircleDiagramRequest)
  })
_sym_db.RegisterMessage(CircleDiagramRequest)

CircleDiagramResponse = _reflection.GeneratedProtocolMessageType('CircleDiagramResponse', (_message.Message,), {
  'DESCRIPTOR' : _CIRCLEDIAGRAMRESPONSE,
  '__module__' : 'plotter_pb2'
  # @@protoc_insertion_point(class_scope:pb.v1.CircleDiagramResponse)
  })
_sym_db.RegisterMessage(CircleDiagramResponse)



_PLOTTER = _descriptor.ServiceDescriptor(
  name='Plotter',
  full_name='pb.v1.Plotter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=496,
  serialized_end=643,
  methods=[
  _descriptor.MethodDescriptor(
    name='BarPlot',
    full_name='pb.v1.Plotter.BarPlot',
    index=0,
    containing_service=None,
    input_type=_BARPLOTREQUEST,
    output_type=_BARPLOTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CircleDiagram',
    full_name='pb.v1.Plotter.CircleDiagram',
    index=1,
    containing_service=None,
    input_type=_CIRCLEDIAGRAMREQUEST,
    output_type=_CIRCLEDIAGRAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLOTTER)

DESCRIPTOR.services_by_name['Plotter'] = _PLOTTER

# @@protoc_insertion_point(module_scope)
