# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.plotter_pb2 as plotter__pb2


class PlotterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BarPlot = channel.unary_unary(
                '/pb.v1.Plotter/BarPlot',
                request_serializer=plotter__pb2.BarPlotRequest.SerializeToString,
                response_deserializer=plotter__pb2.BarPlotResponse.FromString,
                )
        self.CircleDiagram = channel.unary_unary(
                '/pb.v1.Plotter/CircleDiagram',
                request_serializer=plotter__pb2.CircleDiagramRequest.SerializeToString,
                response_deserializer=plotter__pb2.CircleDiagramResponse.FromString,
                )


class PlotterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BarPlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CircleDiagram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BarPlot': grpc.unary_unary_rpc_method_handler(
                    servicer.BarPlot,
                    request_deserializer=plotter__pb2.BarPlotRequest.FromString,
                    response_serializer=plotter__pb2.BarPlotResponse.SerializeToString,
            ),
            'CircleDiagram': grpc.unary_unary_rpc_method_handler(
                    servicer.CircleDiagram,
                    request_deserializer=plotter__pb2.CircleDiagramRequest.FromString,
                    response_serializer=plotter__pb2.CircleDiagramResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.v1.Plotter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Plotter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BarPlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.v1.Plotter/BarPlot',
            plotter__pb2.BarPlotRequest.SerializeToString,
            plotter__pb2.BarPlotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CircleDiagram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.v1.Plotter/CircleDiagram',
            plotter__pb2.CircleDiagramRequest.SerializeToString,
            plotter__pb2.CircleDiagramResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
